# Generated by Django 5.0.6 on 2024-10-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_color_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
